name: Publish Api documentations to GitHub pages

permissions:
  # The SSH key has the write access
  contents: none

on:
    repository_dispatch:
        types: run-build-api-docs
    workflow_dispatch:
    schedule:
        - cron: "00 12 * * *"

jobs:
    publish-pages:
        environment:
            name: API documentations
            url: https://doctum.long-term.support/api-docs/
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ssh-key: ${{ secrets.SSH_KEY_DEPLOY }}
            - name: Import GPG key
              # v6.2.0 - cb9bde2e2525e640591a934b1fd28eef1dcaf5e5
              uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.GPG_PASSPHRASE }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true
            - name: Build docs and push changes
              run: ./scripts/update-built-docs.sh
