name: lint php documentation

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
    lint-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: lint php documentation
              uses: sudo-bot/action-doctum@v5
              with:
                  config-file: scripts/doctum.php
                  method: "parse"
                  cli-args: "--output-format=github --no-ansi --no-progress -v --ignore-parse-errors"
